# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_mainwindow.ui'
#
# Created: Fri Jun  1 14:29:26 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(735, 610)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadButton = QtGui.QPushButton(self.groupBox)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.horizontalLayout.addWidget(self.loadButton)
        self.saveButton = QtGui.QPushButton(self.groupBox)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout.addWidget(self.saveButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toggleOriginalButton = QtGui.QPushButton(self.groupBox)
        self.toggleOriginalButton.setObjectName(_fromUtf8("toggleOriginalButton"))
        self.horizontalLayout.addWidget(self.toggleOriginalButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.imageScrollarea = QtGui.QScrollArea(self.groupBox)
        self.imageScrollarea.setWidgetResizable(True)
        self.imageScrollarea.setAlignment(QtCore.Qt.AlignCenter)
        self.imageScrollarea.setObjectName(_fromUtf8("imageScrollarea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 526))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.imageScrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.imageScrollarea)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.axSlider = QtGui.QSlider(self.tab)
        self.axSlider.setGeometry(QtCore.QRect(10, 40, 160, 19))
        self.axSlider.setMinimum(1)
        self.axSlider.setMaximum(10)
        self.axSlider.setProperty("value", 4)
        self.axSlider.setOrientation(QtCore.Qt.Horizontal)
        self.axSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.axSlider.setTickInterval(1)
        self.axSlider.setObjectName(_fromUtf8("axSlider"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.axSpinbox = QtGui.QSpinBox(self.tab)
        self.axSpinbox.setGeometry(QtCore.QRect(190, 30, 42, 22))
        self.axSpinbox.setReadOnly(True)
        self.axSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.axSpinbox.setObjectName(_fromUtf8("axSpinbox"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sxSpinbox = QtGui.QSpinBox(self.tab)
        self.sxSpinbox.setGeometry(QtCore.QRect(190, 90, 42, 22))
        self.sxSpinbox.setReadOnly(True)
        self.sxSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.sxSpinbox.setObjectName(_fromUtf8("sxSpinbox"))
        self.sxSlider = QtGui.QSlider(self.tab)
        self.sxSlider.setGeometry(QtCore.QRect(10, 100, 160, 19))
        self.sxSlider.setMinimum(1)
        self.sxSlider.setMaximum(10)
        self.sxSlider.setProperty("value", 2)
        self.sxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sxSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.sxSlider.setTickInterval(1)
        self.sxSlider.setObjectName(_fromUtf8("sxSlider"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.aSpinbox = QtGui.QDoubleSpinBox(self.tab)
        self.aSpinbox.setGeometry(QtCore.QRect(190, 140, 42, 22))
        self.aSpinbox.setReadOnly(True)
        self.aSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.aSpinbox.setObjectName(_fromUtf8("aSpinbox"))
        self.aSlider = QtGui.QSlider(self.tab)
        self.aSlider.setGeometry(QtCore.QRect(10, 150, 160, 19))
        self.aSlider.setMinimum(1)
        self.aSlider.setMaximum(10000)
        self.aSlider.setSingleStep(1)
        self.aSlider.setProperty("value", 1000)
        self.aSlider.setOrientation(QtCore.Qt.Horizontal)
        self.aSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.aSlider.setTickInterval(1000)
        self.aSlider.setObjectName(_fromUtf8("aSlider"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.hSlider = QtGui.QSlider(self.tab)
        self.hSlider.setGeometry(QtCore.QRect(10, 210, 160, 19))
        self.hSlider.setMinimum(1)
        self.hSlider.setMaximum(50000)
        self.hSlider.setSingleStep(1)
        self.hSlider.setProperty("value", 1000)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.hSlider.setTickInterval(1000)
        self.hSlider.setObjectName(_fromUtf8("hSlider"))
        self.hSpinbox = QtGui.QDoubleSpinBox(self.tab)
        self.hSpinbox.setGeometry(QtCore.QRect(190, 200, 42, 22))
        self.hSpinbox.setReadOnly(True)
        self.hSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.hSpinbox.setObjectName(_fromUtf8("hSpinbox"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 280, 71, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.maskScrollarea = QtGui.QScrollArea(self.tab)
        self.maskScrollarea.setGeometry(QtCore.QRect(130, 250, 101, 91))
        self.maskScrollarea.setWidgetResizable(True)
        self.maskScrollarea.setAlignment(QtCore.Qt.AlignCenter)
        self.maskScrollarea.setObjectName(_fromUtf8("maskScrollarea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 99, 89))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.maskScrollarea.setWidget(self.scrollAreaWidgetContents_2)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 390, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.timeSpinbox = QtGui.QSpinBox(self.tab)
        self.timeSpinbox.setGeometry(QtCore.QRect(100, 390, 91, 22))
        self.timeSpinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeSpinbox.setReadOnly(True)
        self.timeSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeSpinbox.setMaximum(999999999)
        self.timeSpinbox.setObjectName(_fromUtf8("timeSpinbox"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 420, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fpsSpinbox = QtGui.QDoubleSpinBox(self.tab)
        self.fpsSpinbox.setGeometry(QtCore.QRect(100, 420, 91, 22))
        self.fpsSpinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fpsSpinbox.setReadOnly(True)
        self.fpsSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.fpsSpinbox.setDecimals(1)
        self.fpsSpinbox.setMaximum(100000.0)
        self.fpsSpinbox.setObjectName(_fromUtf8("fpsSpinbox"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 450, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.mpixSpinbox = QtGui.QDoubleSpinBox(self.tab)
        self.mpixSpinbox.setGeometry(QtCore.QRect(100, 450, 91, 22))
        self.mpixSpinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mpixSpinbox.setReadOnly(True)
        self.mpixSpinbox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.mpixSpinbox.setDecimals(2)
        self.mpixSpinbox.setMaximum(100000.0)
        self.mpixSpinbox.setObjectName(_fromUtf8("mpixSpinbox"))
        self.resetButton = QtGui.QPushButton(self.tab)
        self.resetButton.setGeometry(QtCore.QRect(10, 500, 75, 23))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NLMeans", None))
        self.groupBox.setTitle(_translate("MainWindow", "Image", None))
        self.loadButton.setText(_translate("MainWindow", "Load", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.toggleOriginalButton.setText(_translate("MainWindow", "Toogle Original", None))
        self.label.setText(_translate("MainWindow", "Window Size (AX, AY)", None))
        self.label_2.setText(_translate("MainWindow", "Support Size (SX, SY)", None))
        self.label_3.setText(_translate("MainWindow", "Gaussian Mask stdev (A)", None))
        self.label_4.setText(_translate("MainWindow", "Filtering Strength (H)", None))
        self.label_5.setText(_translate("MainWindow", "Mask Preview", None))
        self.label_6.setText(_translate("MainWindow", "Rendering time", None))
        self.timeSpinbox.setSuffix(_translate("MainWindow", " ms", None))
        self.label_7.setText(_translate("MainWindow", "Frame rate", None))
        self.fpsSpinbox.setSuffix(_translate("MainWindow", " fps", None))
        self.label_8.setText(_translate("MainWindow", "Throughput", None))
        self.mpixSpinbox.setSuffix(_translate("MainWindow", " MPix/s", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))

